### ISSUE TITLE
Printing uses a lot of ink

### ISSUE THREAD

**Issue by iroha7941** [Entanglion/entanglion#1]
Printing the game uses a lot of ink, since the backgrounds are predominantly black.  It would be more ecological and cost-friendly to make a version that was the same but instead used white backgrounds (but please keep the original version as well so that users have a choice).

**Comment by maryamashoori** [comment]
Excellent suggestion. I'll add a light version to the game assets.

**Comment by jweisz** [comment]
@iroha7941 Entanglion v1.2 has just been released with a light-themed version of the game assets. Enjoy!

https://github.com/Entanglion/entanglion/releases/tag/v1.2

**Comment by vivekadi** [comment]
wow that was fast
