### ISSUE TITLE
Game Crafter Copy Feedback

### ISSUE THREAD

**Issue by geemus** [Entanglion/entanglion#11]
Some minor feedback about the gamecrafter rule book. I didn't see anything in the repo to offer direct edits to, so I'll just try to describe the issues in english below:

1. On page 11 the detection rate image overlaps with the final paragraph in the second column, cutting off the top portion of the letters.
2. On page 14, the second column ends in "who sold the meticulously-tuned", but the sentence/paragraph doesn't finish. Instead it starts a new paragraph on the following page. From assets in repo it looks like it should conclude: "instruments as scrap metal."

I hope to play and discuss with the local paperswelove chapter soon, will let you know if we have further feedback. Thanks!

**Comment by maryamashoori** [comment]
Hey Wesley,

Thanks for catching these! I just fixed the rulebook on GameCrafter. I agree, I wish they were offering a direct edit access! :-/

**Comment by geemus** [comment]
Sounds good, thanks!
