### ISSUE TITLE
the meaning of omega in Entanglion

### ISSUE THREAD

**Issue by jerejesse** [Entanglion/entanglion#12]
Hello,

I played Entanglion yesterday. An interesting game, I appreciate the mechanics of the game.
However, I don't understand what omega zero one two three stand for.

In the game, I can achieve these planets(states) by applying specific engine(gate) which I suppose is design for some reason.
After a little research I understand what bell states are and why cnot gate can entangle qubits into these states , but I just can't find any resource tell me more about anything omega states.
I read the article "Entanglion: A Board Game for Teaching the Principles of Quantum Computing". It says these states don't have common name, guess that's the reason I can't google it out.
I also read that it is not easy work to calculate the math of transition, is that mean the lack of explanation is due to it's too hard to explain in a few words?

**I think if the game have more information about omega states would be great.**

PS,
I play the game in the hope that I can learn how quantum computer works. And I did learn a lot, like how qubits are manipulated and those important quantum gate. but somehow I still don't know how quantum computer works.
It's like, OK, I can manipulate the qubit to those states now, then what can I do? I get my qubits to psi plus, what does it mean to me?
But maybe I gone too far, this is not what the game designed for, I should go take some courses to learn these things.
so let's just focus on what omega states stand for. really curious about that.

**Comment by jweisz** [comment]
This is a fantastic question, and I'm very happy that you enjoyed the game and are interested in learning more about quantum!

I've referred your question to the quantum scientist who actually did the math behind mapping out all the quantum states, so we'll be able to get back to you with a more technical explanation.

In the meantime, you are correct that the quantum states (represented by planets) in the game are those that can be achieved with our (small) set of quantum gates (X, H, CNOT, SWAP). But, the board is actually a simplification of the actual number of entanglement states that can be achieved with those gates (which is larger than 8, but I forget the actual number). Due to some symmetries between the states, we were able to "collapse" them all together to form the Omega states. And since those states don't have well-known names (unlike the Bell states), we came up with our own names.

As far as to where to go next, I would encourage you to start reading through the [IBM Q Beginner's Guide](https://quantumexperience.ng.bluemix.net/qx/tutorial) and start experimenting with the actual quantum computer.

One of the most important lessons we aimed to teach with this game is about entanglement -- what it is and how it is created. It seems like you have a good understanding of it, and I'd say the next step is to go create it for real! ;)

Thanks again for your question, I'm really happy to see that you enjoyed our game and are motivated to learn more about quantum science!

**Comment by jerejesse** [comment]
I am reading it right now, thanks for telling me the site.

BTW, I am wondering why does some path are only available to either Rubicon or Mercurial.
I suppose the two qubits are exactly identical as we can swap them? and therefore should always able to perform the same action.
Is it for making the game more fun or there is some physical meaning in it?

**Comment by maryamashoori** [comment]
The Centarious galaxy represents the classical states of 0 and 1 (similar to a classical computer). In that galaxy, a swap action actually swaps the value of the two qubits. 


In the quantum world though, it's a little bit different. Two entangled qubits expose behaviors that are different from a classical world. It often matters which qubit an operator is applied to. You can think of a lead spaceship vs a support spaceship. Lead and support in the world of quantum are referred to as `control` and `target`. 

So the short answer is yes, there is a reason that a path may be available only to a particular spaceship.

To read more, please check out the `"Multi-Qubit Gates"` on the [Beginners Guide](https://quantumexperience.ng.bluemix.net/qx/tutorial?page=006-Multi-Qubit_Gates~2F001-Multi-Qubit_Gates).

**Comment by jerejesse** [comment]
https://www.pythonanywhere.com/gists/a5d885816f7dc042a78df11ce6cf9652/main.py/ipython3/
The notation in this tool is more convenient in showing the entanglement of two qubit than Q experience.
I use the sandbox in this tool to figure out how does each omega states mean and why some path are only available to one spaceship(after I notice the path is symmetric to omega two and one).

PHI PLUS: measurement of the two qubit will always have the same result.
PHI MINUS:  measurement of the two qubit will always have the same result, too. But measurement after a hadamard gate will always be opposite.
PSI MINUS: measurement of the two qubit will always be opposite. if Rubicon get one, Mercurial get zero, vise versa.
PSI PLUS: measurement of the two qubit will always be opposite. But measurement after a hadamard gate will always be the same.
**The entanglement doesn't mean they have same value, instead it means one result can lead to another.**

If we list the omega here...
OMEGA TWO: measurement of one qubit and measurement of another qubit after a hadamard gate will always the same.
OMEGA ZERO: measurement of Rubicon and measurement of Mercurial after a hadamard gate will always opposite. If the role exchange, the result will be same.
OMEGA THREE: the role exchange. Measurement of Mercurial and measurement of Rubicon after a hadamard gate will always opposite. If the role exchange, the result will be same.
OMEGA ONE: measurement of a qubit and measurement of another after a hadamard gate will always be opposite.

**Although you said there is actually more states than 8, through the gates available in this game these 8 states are all the states we can achieve. And I think you list all the possible paths on the board !**

I also understand the reason that only the one in Centarious can apply cnot to enter Entanglion.
**control must be in superposition so that entanglement can happen.**

Thanks.

**Comment by jerejesse** [comment]
Suddenly find another possible path not on the board.

If Rubicon use cnot when both Rubicon and Mercurial are minus, it seems that Mercurial should go to plus.
I observe this phenomenon on Q experience, but can't understand the reason.
As I know cnot apply a X gate to target when controll is |1>, but it apply an Z gate to control in this case.

I'll keep studying to find out why does this happen.
Go back to Entanglion, I guess this phenomenon do exist, why doesn't show on the board?

**Comment by jedbrody** [comment]
I've tried to answer these kinds of questions here:  http://physics.emory.edu/faculty/brody/Hidden_Structure_of_Entanglion.pdf

**Comment by maryamashoori** [comment]
@jedbrody Hi Jed, this is awesome! This article will be particularly useful to those profs that use Entanglion as an educational tool in their classes. Can I invite you to publish this as a medium story on qiskit blog? https://medium.com/qiskit  I just spoke with the Qiskit team, we can make this happen.

**Comment by jedbrody** [comment]
Yes, certainly, I'm happy to publish it on the qiskit blog.  How do I do that?

**Comment by maryamashoori** [comment]
I just sent an email to your emory email. I hope I got the email right!
