### ISSUE TITLE
add Russian language

### ISSUE THREAD

**Issue by Izya12** [Entanglion/entanglion#13]
Hello.
Is it planned to add Russian?
I would like to be able to download the rules and the game itself in Russian.
Thanks in advance.

**Comment by AZAZ59** [comment]
Hi!
I want to try translate it to Russian.
If you wont to help, you can join in my fork.

**Comment by maryamashoori** [comment]
Hi @Izya12 There is no official plan to translate Entanglion to other languages, though some friends of Entanglion have been working on translating it to different languages. That would be great if you and @AZAZ59 could help to translate it to Russian. I don't speak Russian but will be happy to help you with updating the graphics.

I'll close this issue for now. Please feel free to reopen if needed. Thanks!
