### ISSUE TITLE
Unclear  Orbital defense rule.

### ISSUE THREAD

**Issue by Unimax** [Entanglion/entanglion#15]
when in entanglion one engine card by one player can move the ships to 2 different planets. so both have to roll the dice? or only once is enough. also if both ships move together then also does dice roll by one player also clear the orbital defenses for the other ship on the new planet?

**Comment by maryamashoori** [comment]
@Unimax When in Entanglion, the two ships are entangled and act as one, you can think of a squad that moves together. If one player moves or defends the orbital defenses, it’s applied to the entire squad (both ships move). Does this answer your question?

**Comment by Unimax** [comment]
@maryamashoori thanks for the reply. what about groud defenses if two ships lands on 2 new planets will rolling for one planet's ground defense will extract both planet's Q Component?

Most of the people complain about the role of luck in the game is too high also. any solution to that. anyway, you can close the issue thanks.
