### ISSUE TITLE
Confusing instruction in the mechanic card.

### ISSUE THREAD

**Issue by frankmireles** [Entanglion/entanglion#2]
It says "play up to two" so, does it means you can decide wether you play one or two? Or you must play 2 out of 3 as an obligation? It also says "Discard the unplayed engine card." Which makes me think you must play 2 out of 3 as an obligation. Help us out!

**Comment by maryamashoori** [comment]
Hi Frank, thanks for your question! The language "play up to two" is supposed to suggest that you can play zero, one, or two engine cards, and discard the rest.
