### ISSUE TITLE
Printer friendly rulebook

### ISSUE THREAD

**Issue by rswhiting** [Entanglion/entanglion#3]
Thank you so much for making a printer-friendly board. Could you also make the rulebook in light-colors? I know I can use the pdf, but I'd like to have the rulebook in the box.

**Comment by maryamashoori** [comment]
@rswhiting 
Entanglion v1.3 has just been released with a light-themed version of the rulebook. Enjoy!

https://github.com/Entanglion/entanglion/releases/tag/v1.3

**Comment by rswhiting** [comment]
You guys rock! I'm looking forward to introducing it to my work lunch gaming group.
