### ISSUE TITLE
ISO 216 paper sizes?

### ISSUE THREAD

**Issue by frankier** [Entanglion/entanglion#4]
It might be nice to have the assets available in ISO 216 paper sizes, as used outside of the US. I think it should be reasonably easy to resize to A4 and A2.

**Comment by xanderbo** [comment]
+1
I found the game very hard to print with A4 paper.

**Comment by maryamashoori** [comment]
Hi Frankie/Aleksander, 
We should be able to create the assets for A4. I'll look into that today.

**Comment by maryamashoori** [comment]
@frankier @xanderbo 

[Entanglion (A4, Light).pdf](https://github.com/Entanglion/entanglion/files/2189202/Entanglion.A4.Light.pdf)
[Entanglion (A4).pdf](https://github.com/Entanglion/entanglion/files/2189203/Entanglion.A4.pdf)

These two versions are for A4 but I don't have A4 paper to test them. Please do a test print and let me know if they look fine. Then I can publish them in a new release. Thanks!

**Comment by maryamashoori** [comment]
Alrightie, Entanglion v1.3 has just been released with a version for A4 paper. Enjoy!

https://github.com/Entanglion/entanglion/releases/tag/v1.3

**Comment by xanderbo** [comment]
I tested the new PDFs and it looks good. See the pictures:
![test_print_player_board](https://user-images.githubusercontent.com/16539313/42688088-41b40d96-869b-11e8-8359-04a7c2bed09f.jpg)
![test_print_board](https://user-images.githubusercontent.com/16539313/42688089-421cad10-869b-11e8-84ae-6faeede4b2e1.jpg)
