### ISSUE TITLE
Separate PDF for separate components

### ISSUE THREAD

**Issue by xanderbo** [Entanglion/entanglion#5]
Hi
I've found the game interesting, however it would be great if you can divide the components into separate PDF files:
- cards
- tokens
- players' boards
- main board

At the moment I'm not able to print the cards which are not cut in half :-/

**Comment by maryamashoori** [comment]
@xanderbo Entanglion v1.3 has just been released with a version for A4 paper. Does this solve the problem? 
https://github.com/Entanglion/entanglion/releases/tag/v1.3

**Comment by xanderbo** [comment]
No much to be honest... I have problems printing the "poster": whatever I do the cutting lines goes through cards or player boards in the way that it is hard to combine them (especially cards). See the picture.
![print_and_entanglion__poster__pdf](https://user-images.githubusercontent.com/16539313/42680850-757709a4-8686-11e8-867a-49abce8dabae.png)

**Comment by xanderbo** [comment]
Maybe you can just attach the pictures (png or whatever) of the cards and player boards. Would be great to have the main board as separate picture too.

**Comment by xanderbo** [comment]
I deleted my previous comments because I missed that A4 version has the components separated the way I want. Thanks!
