### ISSUE TITLE
Upload PDFs to TheGameCrafter

### ISSUE THREAD

**Issue by Quuxplusone** [Entanglion/entanglion#6]
Hi folks,

Seems like you're not aware of https://www.thegamecrafter.com — but you should be! Right now, in order to play the game, it seems like a person has to

- download the PDFs from GitHub
- find a printer
- find cardstock
- print the PDFs, using the printer, onto the cardstock
- cut the cardstock into cards

and then repeat those steps for the board.
The average board game geek will optimize that workflow into

- download the PDFs from GitHub
- tediously upload the PDFs to GameCrafter
- click "Buy"

You could save the average geek a lot of time by doing the upload process yourselves. Then the "print and play" workflow would be a single click, which would probably increase overall adoption of your game.

**Comment by jweisz** [comment]
Thanks, we'll take a look!

**Comment by vitorio** [comment]
It looks like The Game Crafter also has red rocket, blue rocket, yellow d8, purple d6 (blank, indented, to write your own 1s and 0s onto), and white hexagonal base pieces.  Turning all the PDFs into TGC-specific output for the various card and board formats they offer is a little too much work over having my local FedEx Office print the materials onto cardstock, though.  If it was already on there, I'd order it.

**Comment by maryamashoori** [comment]
@vitorio @Quuxplusone Thanks for the suggestions. We are working on getting the game on TGC but as Vitorio mentioned turning the PDFs into TGC specific output is not that straight forward. In some cases it requires a design change to fit to their sizes and specifications. It takes some time, but it's coming! :)

**Comment by vitorio** [comment]
The Game Crafter pieces arrived today.  They're cute!  Not sure how the sizes compare to the printed materials (I haven't made it over to the print shop yet), but I included a US quarter for reference.

![img_20180806_195036032](https://user-images.githubusercontent.com/336712/43748505-9379e5e2-99b5-11e8-848e-1c0f7629b55a.jpg)

**Comment by maryamashoori** [comment]
I can add the purple D6 to the shopping card but it doesn't seem like it lets us package it with the rest of the game components.

**Comment by jweisz** [comment]
Quick update on this -- we reformatted the game assets for TGC and ordered a sample copy. It should arrive in a few days. Assuming there's no issues, we'll be able to make it publicly available for purchase.  Stay tuned!

**Comment by geemus** [comment]
I look forward to this. I have some experience doing gamecrafter uploads/configurations, in case you have questions (might be able to help). Definitely will make it more accessible (for me anyway), as I was curious to play, but not that keen on the process of creating a copy.

**Comment by jweisz** [comment]
We got our proof back but there were some printing issues. 😬 There are a few fixes we need to make, but we're also discussing how to reduce the cost of the game by using different components or reducing the number of custom cardboard punchouts.  The bad news is that we've got a few paper deadlines coming up so we don't have as many cycles to work on this.  Please bear with us. 😉

**Comment by geemus** [comment]
@jweisz yeah, it definitely took me several iterations to get things how I wanted. Coupled with the long feedback cycle, it can be a bit frustrating. I look forward to hearing more when time allows you to return to it. Thanks for the update.

**Comment by jweisz** [comment]
Hi everyone, I have another update on this. After several other major work deadlines, @maryamashoori and I have reformatted all the game assets to fit TGC's templates, reducing the cost of the game. It's about $42 now, down from like $80 when we were using entirely custom components (yay!).

However, we received the latest proof a few days ago and one of the components -- the spaceship boards -- had completely incorrect laser cuts. We decided to eliminate the laser cuts from them, and I just placed another order to make sure they come out correct. So it might be another week or two before we are able to make the game available for sale, but the good news is it won't break your wallets when it does.  ;)

Thanks for your patience!

**Comment by geemus** [comment]
Thanks for the update and work on this, I look forward to checking it out once you can verify.

**Comment by nayanshah** [comment]
Any luck with the new orders ? :)

**Comment by jweisz** [comment]
@nayanshah what good timing you have!  We received the latest proofs of the spaceship boards the other day and had to make one more tweak. I just did this (post turkey coma) and so everything is FINALLY ready!

Happy Thanksgiving!

https://www.thegamecrafter.com/games/entanglion1

**Comment by geemus** [comment]
@jweisz heads up, I made it to the front of the queue on the game crafter and they contacted me to say there was some issue with the files that they would need designer assistance on before proceeding. So maybe keep an eye out for that message so that we can unstick things. Thanks!

**Comment by vitorio** [comment]
I got the same email today also!

**Comment by jweisz** [comment]
Thanks for the heads up. I just replied to their email, hopefully it gave them the info they needed. I'm not sure why there was an issue, we proofed all of the components before publishing the game. My apologies!

**Comment by geemus** [comment]
@jweisz - yep, no worries. Hopefully it was as easy as that to resolve.

**Comment by geemus** [comment]
@jweisz FWIW, I received a shipment notification today, so it must be sorted out. Thanks again!
