### ISSUE TITLE
Board Image

### ISSUE THREAD

**Issue by admiral142** [Entanglion/entanglion#9]
Would you be able to upload an image of just the board as one piece?  I'd like to have it made by printplaygames.com, but need a single image that I can upload there.  If The Game Crafter will have an option to buy just the board, that would be great as well.

Thanks!

**Comment by maryamashoori** [comment]
![quad-fold-game-board](https://user-images.githubusercontent.com/22402305/48636010-ad340080-e997-11e8-9130-0a8905746c4e.png)
@admiral142 Does this work?

**Comment by admiral142** [comment]
Perfect!  Thank you!
